# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""KVS frame extraction utilities using GetClip + ffmpeg."""

import boto3
import base64
import subprocess
import tempfile
import os
from datetime import datetime, timedelta, timezone

from aws_solution import boto_config

# The producer uploads in short segments (KVS_SEGMENT_SEC=2 on the cloud stack), so
# a window this wide is several fragments — enough that a request landing between
# uploads still finds video, without pulling more than ffmpeg wants to seek through.
_WINDOW_SECONDS = 60

# Half-width of the window used when reaching back to a specific past moment. Wide
# enough to survive fragment boundaries and clock skew, narrow enough that the frame
# we extract is recognisably "then" and not several seconds either side of it.
_OFFSET_SLACK_SECONDS = 5


def _clip_client(stream_name: str, region: str | None = None):
    """An archived-media client bound to this stream's GET_CLIP data endpoint."""
    endpoint = boto3.client(
        "kinesisvideo", region_name=region, config=boto_config()
    ).get_data_endpoint(
        StreamName=stream_name,
        APIName="GET_CLIP",
    )["DataEndpoint"]
    return boto3.client(
        "kinesis-video-archived-media",
        endpoint_url=endpoint,
        region_name=region,
        config=boto_config(),
    )


def _get_clip(stream_name, start, end, region=None) -> bytes | None:
    """Fetch recorded video between two instants. None if the range holds nothing."""
    print(f"GetClip: stream={stream_name}, start={start.isoformat()}, end={end.isoformat()}")
    try:
        response = _clip_client(stream_name, region).get_clip(
            StreamName=stream_name,
            ClipFragmentSelector={
                "FragmentSelectorType": "SERVER_TIMESTAMP",
                "TimestampRange": {
                    "StartTimestamp": start,
                    "EndTimestamp": end,
                },
            },
        )
    except Exception as e:
        # Most often ResourceNotFoundException: nothing was uploaded in this range.
        print(f"GetClip failed: {e}")
        return None

    clip_data = response["Payload"].read()
    print(f"GetClip returned {len(clip_data)} bytes")
    return clip_data or None


def get_latest_frame(stream_name: str, region: str | None = None) -> str | None:
    """Grab the most recent frame from a KVS stream as base64 JPEG.

    Uses GetClip to retrieve recent video, then ffmpeg to extract a frame.
    Returns base64-encoded JPEG string or None if no frames available.
    """
    now = datetime.now(timezone.utc)
    clip_data = _get_clip(stream_name, now - timedelta(seconds=_WINDOW_SECONDS), now, region)
    if not clip_data:
        return None
    return _extract_frame_from_clip(clip_data, position="last")


def get_frame_at_offset(
    stream_name: str, offset_seconds: float, region: str | None = None
) -> str | None:
    """Grab one frame from `offset_seconds` ago as base64 JPEG.

    This is the thing the archive buys you: it works for any moment inside the
    stream's retention (24 h), with no snapshot having been taken at the time. The
    agent's local compare_scenes can only reach moments it happened to look at.

    Returns None if nothing was uploaded around then — the robot may have been off,
    or the moment may be older than retention.
    """
    target = datetime.now(timezone.utc) - timedelta(seconds=offset_seconds)
    clip_data = _get_clip(
        stream_name,
        target - timedelta(seconds=_OFFSET_SLACK_SECONDS),
        target + timedelta(seconds=_OFFSET_SLACK_SECONDS),
        region,
    )
    if not clip_data:
        return None
    # "first" here, not "last": the window straddles the target moment, so its
    # opening frames are the closest thing to it.
    return _extract_frame_from_clip(clip_data, position="first")


def _ffmpeg_one_frame(clip_path: str, output_path: str, seek: list[str]) -> bool:
    """Write one frame of `clip_path` to `output_path`. True if a frame landed.

    The argv list is written out at the call site rather than assembled into a
    variable first. That is deliberate: it keeps the program name visibly a
    literal, which is the property that makes this call safe. It is argv-list
    form with no shell=True, so no shell is spawned and the non-constant
    elements — the two paths and the seek flags — cannot be reinterpreted as
    shell syntax. Both paths are tempfile-generated by the caller in this
    module; neither is caller-supplied.

    Raises CalledProcessError if ffmpeg fails, so a broken clip is not silently
    reported as "no frame".
    """
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            *seek,
            "-i", clip_path,
            "-frames:v", "1",
            "-q:v", "2",
            output_path,
        ],
        timeout=15, check=True, capture_output=True,
    )
    return os.path.exists(output_path) and os.path.getsize(output_path) > 0


def _extract_frame_from_clip(clip_data: bytes, position: str = "last") -> str | None:
    """Extract a single frame from an MP4/MKV clip using ffmpeg."""
    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as clip_file:
        clip_file.write(clip_data)
        clip_path = clip_file.name

    output_path = clip_path + ".jpg"

    # Seek near the end with -sseof (from end, so no ffprobe needed) when the
    # caller wants the last frame. No seek means the first frame.
    seek = ["-sseof", "-2"] if position == "last" else []

    try:
        got = False
        if seek:
            # A seek past the start of a short or truncated clip either produces
            # nothing or makes ffmpeg exit non-zero, depending on the clip. Treat
            # both the same and fall through to the unseeked read below, which is
            # the one place a frame is always available.
            try:
                got = _ffmpeg_one_frame(clip_path, output_path, seek)
            except subprocess.SubprocessError as e:
                print(f"Seek to end failed, falling back to first frame: {e}")
        if not got:
            got = _ffmpeg_one_frame(clip_path, output_path, [])
        if got:
            with open(output_path, "rb") as f:
                return base64.b64encode(f.read()).decode("utf-8")
    except Exception as e:
        print(f"Frame extraction failed: {e}")
    finally:
        _cleanup(clip_path, output_path)

    return None


def _cleanup(*paths):
    for p in paths:
        try:
            if os.path.exists(p):
                os.unlink(p)
        except OSError:
            pass
