# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""Shared singleton holding the active Go2 transport client.

The Strands tools in `tools.py` resolve the robot client through `get_client()`
so they stay transport-agnostic. `main.py` installs a `Go2ROS2Client` via
`set_client()` before the agent starts, routing every command through the
Foxglove WebSocket bridge exposed by this SDK's container.
"""

from typing import Optional, Protocol


class Go2ClientProtocol(Protocol):
    """Structural interface shared by all Go2 transport clients."""

    def stand_up(self) -> dict: ...
    def stand_down(self) -> dict: ...
    def sit(self) -> dict: ...
    def move(self, vx: float, vy: float, vyaw: float, duration: float) -> dict: ...
    def turn_degrees(self, degrees: float, speed: Optional[float]) -> dict: ...
    def stop(self) -> dict: ...
    def perform_special_motion(self, motion_name: str) -> dict: ...
    def describe_scene(self, question: str) -> dict: ...
    def recall_scene(self, question: str, seconds_ago: float) -> dict: ...
    def compare_scenes(self, question: str, seconds_ago: float) -> dict: ...
    def get_state(self) -> dict: ...
    def get_detections(self) -> dict: ...
    def start_tracking(self, target: str) -> dict: ...
    def stop_tracking(self) -> dict: ...
    def find_object(self, target: str) -> dict: ...
    def get_find_status(self) -> dict: ...
    def stop_find(self) -> dict: ...
    def greet_visitor(self, wait_seconds: float) -> dict: ...
    def start_greeter(self) -> dict: ...
    def stop_greeter(self) -> dict: ...
    def get_greeter_status(self) -> dict: ...
    def disconnect(self) -> None: ...


_client_instance: Optional[Go2ClientProtocol] = None


def get_client() -> Go2ClientProtocol:
    """Return the active robot client.

    Raises if no client has been installed yet — `main.py` calls
    `set_client()` during startup, so the tools always have one at run time.
    """
    if _client_instance is None:
        raise RuntimeError(
            "No Go2 client installed. Call set_client() before invoking tools."
        )
    return _client_instance


def set_client(client: Go2ClientProtocol) -> None:
    """Install the shared client (e.g. the ROS2 Foxglove transport)."""
    global _client_instance
    _client_instance = client
